# Generated by Django 4.1.2 on 2022-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(default=None, null=True, to='news.news', verbose_name='Заметки'),
        ),
    ]
