# Generated by Django 4.1.2 on 2022-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('users', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='categories',
            field=models.ManyToManyField(null=True, to='news.categories', verbose_name='Категории'),
        ),
    ]
